### ISSUE TITLE
Consider renaming Tab "Geopackage" to "Model Manager"

### ISSUE THREAD

**Issue by FransRoelofsen** [Deltares/QGIS-Tim#100]
The name geopackage doesn't cover the meaning of the Tab content. Geopackage is the the format of the datafile in which the modeldata is saved/stored. Perhaps this name is a remnant from the first period of developments, focusing on loading and saving the model components. 

Suggestion. While the tab contains options to manage your model (create, open, save, unselect, select, export) perhaps a better name is "Model Manager".  Feel free to suggest alternatives.

Kind regards, 
Frans

**Comment by Huite** [comment]
This seems like a reasonable suggestion. It's not very interesting to the user that the data is being stored as a GeoPackage.

There's another thing which has been bothering me: the steady-state/transient switch changes what is visible in the Attribute Table, but it's visible under the "Compute" tab. This selector should arguably be moved to another tab?

**Comment by Huite** [comment]
Closed by: fa068ee43ac9dcde8658d82bbd42ffd37137026c
