### ISSUE TITLE
Building Pit

### ISSUE THREAD

**Issue by ArtemisRo** [Deltares/QGIS-Tim#105]
I tried to create a model in qgis-tim that includes a Bulding pit in my area.
In the geopackage, two elements _"timml Building pit:ab"_ and _"timml Building pit properties: ab"_ appear.
When I edit them and try to calculate the model I get this error:
**Server error: Response: "None of ['timeseries_id'] are in the columns"**
While all the columns are full with the data.
After this error I can not convert the geopackage to python script.
Is there any problem with this element in qgis-tim?

Regards,

**Comment by Huite** [comment]
I've just pushed 4a3d0ba85c46e8491ac5e4446102674527673cff which includes a fix for this issue.

However, it requires both updating the QGIS plugin and the `gistim` package, so it may be easier to wait for the next release.
