### ISSUE TITLE
Calculate min/max head (within headgrid) as diagnostic information

### ISSUE THREAD

**Issue by MattBrst** [Deltares/QGIS-Tim#112]
In some cases the calculated heads can become unrealistically high or low. Can we add the min/max head (within each layer of the headgrid) as a diagnostic measure?

See [here](https://github.com/mbakker7/timml/issues/63#issuecomment-1516175996), where the head becomes +200 m.

**Comment by Huite** [comment]
The minimum and maximum values are used by default to set the colorbar of both the mesh and raster layers.

A raster layer has some summary statistic, under Properties > Information, in the section "Information from Provider".

Secondly, in all the changes I've been making if contours are automatically exported, they will stretch from the minimum to the maximum. That should hopefully provide enough information.

I will release this in the coming month; feel free to re-open this issue thereafter if you feel it still insufficiently communicated.
