### ISSUE TITLE
Contour lines: Consider truncating values

### ISSUE THREAD

**Issue by JoerivanEngelen** [Deltares/QGIS-Tim#113]
Probably due to some floating point thing, the values of isocontours are not entirely exact. This makes it hard to use a QGIS query filter. Apparently using Raster -> Extraction -> Contour results in truncated values. 

See screenshot below:

![image](https://github.com/Deltares/QGIS-Tim/assets/9744750/07ef5d89-de50-4110-a6e3-506adde04039)

**Comment by Huite** [comment]
Hmmm, I'm somewhat unsure how to address this. The current contours do not go below 0.01, so this is a floating point representation problem indeed.
Rounding this in the attribute table does seem to solve it somehow, which I find baffling...
