### ISSUE TITLE
Suggestion for error handling: save of *.py file by default 

### ISSUE THREAD

**Issue by FransRoelofsen** [Deltares/QGIS-Tim#114]
Errors during running or unclear results can happen. To help finding a clou it might be helpful to save a temporal *.py file with each 'calculate'.   Perhaps a mismatch between layer overview in QGIS and the script may occur.

**Comment by Huite** [comment]
Validation should clarify this. Secondly, if it manages to write properly, a JSON is written now.
Exporting to Python now also happens fully within the plugin.

Roughly implemented in: 3c05195149866cfe130896aa69e93d82a7b00d73
