### ISSUE TITLE
Update packages option from QGIS not working

### ISSUE THREAD

**Issue by MattBrst** [Deltares/QGIS-Tim#124]
When I try the 'Options' button and choose install, I end up with the error message: 'The current user does not have write permissions to the target environment. Environment location: C:\ProgramData\deltaforge.'

I tried to solve this by opening CMD with 'run as administrator', but did not get the Mamba commands working there.

**Comment by Huite** [comment]
The latest version will be a lot simpler to install in terms of the backend, such that pip install gistim should suffice.

Allowing to update from the plugin was rather optimistic on my part. I've ripped out the updating part, the current widget just shows the versions now.

Online docs will be updated accordingly.
