### ISSUE TITLE
Validate input after stopping editing

### ISSUE THREAD

**Issue by JoerivanEngelen** [Deltares/QGIS-Tim#13]
In GitLab by @Huite on Jun 4, 2021, 15:32

When a layer is no longer edited, it's a good opportunity to check the model input.

A number of automated checks would be useful:

* Positive scalar values (on resistance or conductivity)
* Input present in viable layers (not in invalid layers)
* Check geometry (self intersection, duplicate vertices, etc.)

When one of these checks fails, the QGIS message bar can be used to warn the user.

**Comment by Huite** [comment]
Implemented leading up to: 3c05195149866cfe130896aa69e93d82a7b00d73
