### ISSUE TITLE
Heads computed in QGIS-Tim differ from heads computed in TimML

### ISSUE THREAD

**Issue by MattBrst** [Deltares/QGIS-Tim#157]
We encountered a major difference in calculated heads between QGIS-TIM and TimML in Python, see attached file for both the QGIS-TIM geopackage and the exported Python file: [qgistim_python_comparison.zip](https://github.com/user-attachments/files/15902127/qgistim_python_comparison.zip)

In the minimal example provided, there is one Head Observation point. For layer 0, these are the calculated values:

- QGIS-Tim: head = -0.13 m
- TimML: head = -0.30 m

The TimML versions are 6.3.0 (QGIS-Tim) and 6.4.1 (Python).

Any help would be appreciated.

**Comment by Huite** [comment]
Hi @MattBrst,

With the zip you provided, I don't seem to be able to reproduce the issue.

Here are my results, the Python thing running in a Notebook, and the QGIS attribute table showing the computed results:
![image](https://github.com/Deltares/QGIS-Tim/assets/13662783/c02c2c61-1bab-4070-b873-0a41147ea6ef)

As you can see, both show the head of -0.13 in the first layer (and fortunately all the other heads match as well).

I've added a print statement for the observation array and running through my command line:
```
❯ python qgistim_python_comparison.py
Number of elements, Number of equations: 10 , 116
..........
solution complete
[-0.13261507 -0.21128653 -0.3849932  -0.26969505 -0.23609152 -0.22211668
 -0.18587607]
```

It is possible you didn't run the Python script fully, such that one element maybe didn't get added or something?
I'm also on TimML 6.3.0 in QGIS, and 6.4.1 in my Python (technically Github main branch).

**Comment by MattBrst** [comment]
It seems we were running an older version than the one I mentioned in the previous post (6.4.1). After updating the TimML package in the correct environment ;-), we get the same results as you do. 

Thank you and case closed
