### ISSUE TITLE
Explore GeoPackage Related Tables Extension

### ISSUE THREAD

**Issue by JoerivanEngelen** [Deltares/QGIS-Tim#48]
In GitLab by @Huite on Jun 3, 2022, 22:47

See: http://docs.opengeospatial.org/is/18-000/18-000.html

This could provide a better way of relating polygon inhomogeneity properties and transient input to their geometries, rather than the current assocation by name. First question is whether QGIS already supports this extension.

**Comment by Huite** [comment]
It seems like QGIS doesn't...
