### ISSUE TITLE
Validation in backend

### ISSUE THREAD

**Issue by JoerivanEngelen** [Deltares/QGIS-Tim#57]
In GitLab by @Huite on Oct 24, 2022, 10:37

The backend is probably the best place for validation.

Currently, it will only "validate" and err during computation. So for good feedback, we should maybe add an option to validate without computation.

This raises the question where to validate. It would be nice to use pydantic, but the reported errors are Python focused. There should be an easy entry-point however, as all input to (T)Tim(ML) is provided via a kwargs-dict. These dicts can be easily validated using pydantic.

However, some validation on the geodataframes is likely unavoidable. This may have to occur without pydantic.

**Comment by Huite** [comment]
Solved in front-end in #131
