### ISSUE TITLE
Set default values for all mandatory input?

### ISSUE THREAD

**Issue by JoerivanEngelen** [Deltares/QGIS-Tim#78]
In GitLab by @Huite on Mar 7, 2023, 15:54

It's not communicated very clearly which values are required and which are not. This can make it rather difficult to get something setup. It might friendlier to set default values for everything. That way, the model will run.

**Comment by Huite** [comment]
Some of tedious things have gotten a default value (e.g. timeseries_id on observations, inhomogeneity_id).

The rest should probably stay as-is.
